# Generated by Django 3.1.7 on 2021-05-25 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlike',
            name='action',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userlike',
            name='adventure',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userlike',
            name='animation',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userlike',
            name='comedy',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userlike',
            name='crime',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userlike',
            name='documentary',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userlike',
            name='drama',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userlike',
            name='family',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userlike',
            name='fantasy',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userlike',
            name='history',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userlike',
            name='horror',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userlike',
            name='music',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userlike',
            name='mystery',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userlike',
            name='romance',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userlike',
            name='sf',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userlike',
            name='thriller',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userlike',
            name='tvmovie',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userlike',
            name='war',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userlike',
            name='western',
            field=models.IntegerField(default=0),
        ),
    ]
